apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memory-pwa
  namespace: argocd
  labels:
    app: memory-pwa
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/memory-pwa.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: memory-pwa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
  revisionHistoryLimit: 3
