apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-pwa
  namespace: memory-pwa
  labels:
    app: memory-pwa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-pwa
  template:
    metadata:
      labels:
        app: memory-pwa
    spec:
      containers:
      - name: memory-pwa
        image: anihilat/pwa-memory:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
      resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5


